### Will allow the inclusion of the correct CPU makefile
CPU_FAMILY = cc13xx

### Include the common sensortag makefile
include $(PLATFORM_ROOT_DIR)/attom/Makefile.attom

CONTIKI_TARGET_DIRS += attom/cc1310
