#ifndef PROJECT_CONF_H
#define PROJECT_CONF_H

#define RF_CORE_CONF_CHANNEL 26
#define DOT_15_4G_CONF_FREQUENCY_BAND_ID DOT_15_4G_FREQUENCY_BAND_915
#define IP64_CONF_DHCP 1

#endif // PROJECT_CONF_H
