CFLAGS += -DBOARD_SMARTRF06EB=1 -DBOARD_ATTOM=1
#CFLAGS += -DUIP_FALLBACK_INTERFACE=ip64_uip_fallback_interface

CONTIKI_TARGET_DIRS += attom

BOARD_SOURCEFILES += leds-arch.c srf06-sensors.c button-sensor.c board.c enc28j60-arch-gpio-driver.c

MODULES += dev/enc28j60
MODULES += core/net/ip64
